run prettier on new workflow files

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -7,29 +7,29 @@ jobs:
   check-image-exists:
     runs-on: ubuntu-latest
     steps:
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_KEY }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
-        aws-region: eu-west-1
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_KEY }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
+          aws-region: eu-west-1
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v1
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
 
-    - name: Check that image exists
-      env:
-        ECR_REPOSITORY: mastodon
-        IMAGE_TAG: ${{ github.ref_name }}
-      run: |
-        TAG_FOUND=$(echo $(aws ecr list-images --repository-name mastodon --query "imageIds[?imageTag=='$IMAGE_TAG'].imageTag" --output text))
-        if [[ $TAG_FOUND ]]; then
-          echo "$IMAGE_TAG: Tag found"
-        else
-          echo "$IMAGE_TAG: Tag not found"
-          exit 1
-        fi
+      - name: Check that image exists
+        env:
+          ECR_REPOSITORY: mastodon
+          IMAGE_TAG: ${{ github.ref_name }}
+        run: |
+          TAG_FOUND=$(echo $(aws ecr list-images --repository-name mastodon --query "imageIds[?imageTag=='$IMAGE_TAG'].imageTag" --output text))
+          if [[ $TAG_FOUND ]]; then
+            echo "$IMAGE_TAG: Tag found"
+          else
+            echo "$IMAGE_TAG: Tag not found"
+            exit 1
+          fi
 
   deploy-prod:
     name: production
